#!/bin/sh
mkdir -p /var/cache/snooze
exec snooze -w 0 -s 7d -t /var/cache/snooze/weekly -- sh -c \
	"test -d /etc/cron.weekly && run-parts --lsbsysinit /etc/cron.weekly; touch /var/cache/snooze/weekly"
