#!/bin/sh
mkdir -p /var/cache/snooze
exec snooze -d 1 -s 28d -t /var/cache/snooze/monthly -- sh -c \
	"test -d /etc/cron.monthly && run-parts --lsbsysinit /etc/cron.monthly; touch /var/cache/snooze/monthly"
